## 학습목표
- 브로드캐스팅의 이해

In [1]:
import numpy as np

### 브로드캐스팅
- Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
- 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드캐스팅(Shape을 맞춤)후 진행

### 브로드캐스팅 Rule
- [공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
- 뒷 차원에서 부터 비교하여 Shape 같거나, 차원 중 값이 1인 것이 존재하면 가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg

- Shape이 같은 경우의 연산

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.08830739 0.94391949 0.83416488 0.01632768 0.3404932 ]
 [0.58005732 0.62403949 0.98956896 0.07389295 0.39968157]
 [0.5439331  0.6654784  0.23644362 0.43570661 0.77026094]]


In [3]:
x + y

array([[ 0.08830739,  1.94391949,  2.83416488,  3.01632768,  4.3404932 ],
       [ 5.58005732,  6.62403949,  7.98956896,  8.07389295,  9.39968157],
       [10.5439331 , 11.6654784 , 12.23644362, 13.43570661, 14.77026094]])

- Scalar(상수)와의 연산

In [4]:
x + 2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [5]:
x * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [6]:
x ** 2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [7]:
x % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

- Shape이 다른 경우 연산

In [16]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)
c = np.arange(1000, 1004)
d = b.reshape(1, 3)

print(a)
print(b)
print(c)
print(d)

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]
[1000 1001 1002 1003]
[[100 101 102]]
(4, 3)
(3,)
(4,)
(1, 3)


In [11]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [13]:
a + c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [17]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])