## 학습목표
- numpy에서 자주 사용되는 함수들을 사용해 보기

In [1]:
import numpy as np

### numpy documentation
- [numpy 공식 문서 링크](https://numpy.org/doc/stable/reference/index.html#reference)
- numpy에서 제공되는 함수등에 대한 문서

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)

print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.91945394 0.719972   0.02470771 0.94568221 0.64879224]
 [0.73187213 0.4949088  0.75272357 0.82108809 0.25016308]
 [0.41942228 0.71138602 0.64990656 0.64381743 0.34702887]]


### 연산함수
- add, substract, multiply, divide

In [3]:
np.add(x, y)

array([[ 0.91945394,  1.719972  ,  2.02470771,  3.94568221,  4.64879224],
       [ 5.73187213,  6.4949088 ,  7.75272357,  8.82108809,  9.25016308],
       [10.41942228, 11.71138602, 12.64990656, 13.64381743, 14.34702887]])

In [4]:
np.subtract(x, y)

array([[-0.91945394,  0.280028  ,  1.97529229,  2.05431779,  3.35120776],
       [ 4.26812787,  5.5050912 ,  6.24727643,  7.17891191,  8.74983692],
       [ 9.58057772, 10.28861398, 11.35009344, 12.35618257, 13.65297113]])

In [5]:
np.multiply(x, y)

array([[0.        , 0.719972  , 0.04941541, 2.83704663, 2.59516898],
       [3.65936063, 2.96945283, 5.26906499, 6.56870472, 2.25146773],
       [4.19422282, 7.82524618, 7.79887868, 8.36962659, 4.85840418]])

In [6]:
np.divide(x, y)

array([[ 0.        ,  1.38894291, 80.94640836,  3.17231303,  6.16530181],
       [ 6.83179454, 12.12344566,  9.29956265,  9.74316897, 35.97653168],
       [23.84231938, 15.46277232, 18.46419285, 20.19205972, 40.34246488]])

In [7]:
x + y

array([[ 0.91945394,  1.719972  ,  2.02470771,  3.94568221,  4.64879224],
       [ 5.73187213,  6.4949088 ,  7.75272357,  8.82108809,  9.25016308],
       [10.41942228, 11.71138602, 12.64990656, 13.64381743, 14.34702887]])

In [9]:
x - y

array([[-0.91945394,  0.280028  ,  1.97529229,  2.05431779,  3.35120776],
       [ 4.26812787,  5.5050912 ,  6.24727643,  7.17891191,  8.74983692],
       [ 9.58057772, 10.28861398, 11.35009344, 12.35618257, 13.65297113]])

In [10]:
x * y

array([[0.        , 0.719972  , 0.04941541, 2.83704663, 2.59516898],
       [3.65936063, 2.96945283, 5.26906499, 6.56870472, 2.25146773],
       [4.19422282, 7.82524618, 7.79887868, 8.36962659, 4.85840418]])

In [11]:
x / y

array([[ 0.        ,  1.38894291, 80.94640836,  3.17231303,  6.16530181],
       [ 6.83179454, 12.12344566,  9.29956265,  9.74316897, 35.97653168],
       [23.84231938, 15.46277232, 18.46419285, 20.19205972, 40.34246488]])

### 통계함수
- 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [12]:
print(y)

[[0.91945394 0.719972   0.02470771 0.94568221 0.64879224]
 [0.73187213 0.4949088  0.75272357 0.82108809 0.25016308]
 [0.41942228 0.71138602 0.64990656 0.64381743 0.34702887]]


In [13]:
np.mean(y)

0.6053949953081699

In [14]:
y.mean()

0.6053949953081699

In [15]:
np.max(y)

0.9456822103865653

In [16]:
np.argmax(y)

3

In [17]:
np.var(y)

0.060352700766181114

In [18]:
np.median(y)

0.6499065569038035

In [19]:
np.std(y)

0.24566786677581812

### 집계함수
- 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [20]:
print(y)

[[0.91945394 0.719972   0.02470771 0.94568221 0.64879224]
 [0.73187213 0.4949088  0.75272357 0.82108809 0.25016308]
 [0.41942228 0.71138602 0.64990656 0.64381743 0.34702887]]


In [21]:
np.sum(y)

9.080924929622547

In [22]:
np.cumsum(y)

array([0.91945394, 1.63942594, 1.66413365, 2.60981586, 3.2586081 ,
       3.99048023, 4.48538903, 5.2381126 , 6.05920069, 6.30936377,
       6.72878606, 7.44017207, 8.09007863, 8.73389606, 9.08092493])

In [23]:
sum(y)

array([2.07074835, 1.92626682, 1.42733783, 2.41058773, 1.2459842 ])

In [24]:
np.sum(y, axis=0)

array([2.07074835, 1.92626682, 1.42733783, 2.41058773, 1.2459842 ])

In [25]:
np.sum(y, axis=1)

array([3.2586081 , 3.05075567, 2.77156116])

### any, all 함수
- any : 특정 조건을 만족하는 원소가 하나라도 있으면 True, 아니면 False
- all : 모든 원소가 특정조건을 만족한다면 True, 아니면 False

In [27]:
z= np.random.randn(10)
print(z)

[ 2.11055193 -0.67786523 -1.23704694  1.75022379 -0.62456903  0.6224586
 -1.03669782  1.82396797 -0.09950131 -0.94344779]


In [29]:
z > 0

array([ True, False, False,  True, False,  True, False,  True, False,
       False])

In [28]:
np.any(z > 0)

True

In [30]:
np.all(z > 0)

False

In [31]:
np.all(z != 0)

True

### where 함수
- 조건에 따라 선별적으로 값을 선택 가능
- 사용 예) 음수인 경우는 0,  나머지는 그대로 값을 쓰는 경우

In [32]:
z = np.random. randn(10)
print(z)

[ 0.96894782  0.55154041  1.24071876 -0.53753341  0.18790515  1.4347166
 -0.38263879 -0.12174885  0.65635463 -1.67999014]


In [33]:
np.where(z > 0 , z, 0)

array([0.96894782, 0.55154041, 1.24071876, 0.        , 0.18790515,
       1.4347166 , 0.        , 0.        , 0.65635463, 0.        ])