## 학습목표
- linalg 서브모듈 함수를 활용하여 선형대수 연산하기

In [1]:
import numpy as np

### np.linalg.inv
- 역행렬을 구할때 사용
- 모든 차원의 값이 같아야 함

In [8]:
x = np.random.rand(3, 3)  #정방행렬만 가능
print(x)


y = np.linalg.inv(x)
print(y)

print(np.matmul(x, y))
print(x @ y)

[[0.60176423 0.7955927  0.56847058]
 [0.91725354 0.27341582 0.77776564]
 [0.57271834 0.66122571 0.64335399]]
[[ 5.37445004  2.15947163 -7.35952475]
 [ 2.29793578 -0.97798394 -0.84815918]
 [-7.14614413 -0.91722581  8.97757622]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.88178420e-16  1.00000000e+00  0.00000000e+00]
 [-8.88178420e-16  1.11022302e-16  1.00000000e+00]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.88178420e-16  1.00000000e+00  0.00000000e+00]
 [-8.88178420e-16  1.11022302e-16  1.00000000e+00]]


### np.linalg.solve
- Ax = B 형태의 선형대수식 솔루션을 제공
- 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
    - x + y = 25
    - 2x + 4y = 64

$$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [11]:
A = np.array([[1, 1], [2, 4]])
B = np.array([25, 64])

x = np.linalg.solve(A, B)
print(x)

np.allclose(A@x, B)

[18.  7.]


True