## 학습목표
- Boolean indexing으로 조건에 맞는 데이터 선택하기

In [1]:
import numpy as np

### Boolean indexing
- ndarray 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링

- 브로드캐시팅을 활용하여 ndarray로부터 bool 리스트 얻기
    - 예) 짝수인 경우만 찾아보기

In [2]:
x = np.random.randint(1, 100, size=10)
print(x)

[84 24 40  3 97 35 83 39 99 93]


In [6]:
even_mask = x % 2 == 0
print(even_mask)

[ True  True  True False False False False False False False]


- bool 리스트를 인덱스로 전달

In [5]:
x[even_mask]

array([84, 24, 40])

In [7]:
x[x % 2 == 0]

array([84, 24, 40])

In [8]:
x[x > 30]

array([84, 40, 97, 35, 83, 39, 99, 93])

### 다중조건 사용하기
- 파이썬 논리 연산자인 and, or, not 키워드 사용불가
- & - AND
- | - OR

In [10]:
x[(x % 2 == 0) & (x < 30)]

array([24])

In [11]:
x[(x < 30) | (x > 50)]

array([84, 24,  3, 97, 83, 99, 93])

### (예제) 2019년 7월 서울 평균기온 데이터
- 평균기온이 25도를 넘는 날수는?
- 평균기온이 25도를 넘는 날의 평균 기온은?

In [12]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6,
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9,
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5,
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [17]:
len(temp[temp > 25.0])

21

In [16]:
np.sum(temp > 25.0)

21

In [18]:
np.mean(temp[temp > 25])

26.857142857142858